# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SeraiOS' do
pod 'UIView+Shimmer'
end

target 'SeraiOSTests' do

end

target 'SeraiOSUITests' do

end

